services:
  anki-sync-server:
    image: 762233731293.dkr.ecr.ap-northeast-2.amazonaws.com/tonynamy/anki-sync-server:24.11
    volumes:
      - ${HOST_DATA_PATH}:/anki_data
    ports:
      - 8080:8080
    env_file:
      - .env